# Generated by Django 4.2.7 on 2023-12-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('uuid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('parent_number', models.CharField(max_length=25)),
                ('typef', models.CharField(max_length=3)),
                ('namef', models.CharField(max_length=128)),
                ('file_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('load_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='decimalnumbers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
